kafka:
  global:
    bootstrap.servers: 192.168.0.254:29092
  schema-registry-url: http://192.168.0.254:8081
  state-dir: target
  application-id: household-finance


spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:file:~/finance-db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true